# Base URL for the MAS admin API (without the trailing /v1 portion)
admin_api: "https://mas.example.com/api/admin"
# OAuth2 token endpoint for MAS
token_url: "https://mas.example.com/oauth2/token"
# OAuth client credentials for MAS admin API access
client_id: ""
client_secret: ""
# Scope requested when fetching access tokens
token_scope: "urn:mas:admin"
# Base command without the prefix (!).
base_command: token
# Default allowed uses per token
default_uses_allowed: 1
# Default expire time per generated token 7days=604800s
default_expiry_time: 604800
# The list of user IDs who are allowed to talk to the bot. There is absolutely no
# sandboxing in maubot or this plugin, keep this list small.
whitelist:
- '@user:example.com'
# Optional list of room IDs whose members may use the bot in-room.
room_whitelist:
- '!roomid:example.com'
