name: Build plugin archive

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build plugin archive
        run: |
          chmod +x worker
          ./worker build --out dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maubot-plugin
          path: dist/*.mbp
